POST http://localhost:3000/beers/
Content-Type: application/json

{
    "name": "birra",
    "tagline": "birra",
    "first_brewed":"birra",
    "description":"birra",
    "attenuation_level":3,
    "brewers_tips": "birra",
    "contributed_by": "birra"
    
}